SHELL := /bin/sh

.DEFAULT_GOAL := all

# Root directory (resolve from this Makefile path, supports out-of-tree wrapper include)
MAKEFILE_PATH := $(lastword $(MAKEFILE_LIST))
ROOT_DIR := $(patsubst %/,%,$(dir $(abspath $(MAKEFILE_PATH))))

# Optional config generated by ./configure
CONFIG_MK ?= config.mk
-include $(CONFIG_MK)

# Build output directory (override: make BUILD_DIR=out)
BUILD_DIR ?= build
BUILD_DIR_ABS := $(abspath $(CURDIR)/$(BUILD_DIR))

# Install directories (override in config.mk or make variables)
PREFIX ?= /usr/local
EXEC_PREFIX ?= $(PREFIX)
BINDIR ?= $(EXEC_PREFIX)/bin
LIBDIR ?= $(EXEC_PREFIX)/lib
XLANG_LIBDIR ?= $(LIBDIR)/xlang
INSTALL ?= install
INSTALL_PROGRAM ?= $(INSTALL) -m 0755
INSTALL_DATA ?= $(INSTALL) -m 0644

# Parse make parallel flag, e.g. `make -j8` or `make --jobs=8`
MAKE_JOBS_LONG := $(patsubst --jobs=%,%,$(filter --jobs=%,$(MAKEFLAGS)))
MAKE_JOBS_SHORT := $(patsubst -j%,%,$(filter -j%,$(MAKEFLAGS)))
MAKE_JOBS := $(firstword $(filter-out ,$(MAKE_JOBS_LONG) $(MAKE_JOBS_SHORT)))

# Parallel jobs (default: from make -j, otherwise CPU count)
JOBS ?= $(if $(MAKE_JOBS),$(MAKE_JOBS),$(shell (command -v nproc >/dev/null 2>&1 && nproc) || (getconf _NPROCESSORS_ONLN 2>/dev/null) || echo 8))

# Optional pre-build metadata refresh.
# Use: make CABAL_UPDATE=1 all
CABAL_UPDATE ?= 0
CABAL ?= cabal

# xlang std compile jobs for libs/java
# override explicitly if needed: make java_lib XLANG_JOBS=9
XLANG_JOBS ?= $(JOBS)

# Haskell compiler (Cabal)
COMPILER_DIR := $(ROOT_DIR)/compiler
EXE := xlang
ifeq ($(OS),Windows_NT)
EXE_FILE := $(EXE).exe
else
EXE_FILE := $(EXE)
endif
EXE_OUT := $(BUILD_DIR_ABS)/$(EXE_FILE)
EXE_OUT_GRADLE := $(subst \,/,$(EXE_OUT))

# Java tool (Gradle)
BYTECODEGEN_DIR := $(ROOT_DIR)/tools/BytecodeToolkit
ICONTOOLKIT_DIR := $(ROOT_DIR)/tools/IconToolkit
TOOLS_OUT_DIR := $(BUILD_DIR_ABS)/tools
ICON_SVG := $(ROOT_DIR)/images/icon.svg
ICONTOOLKIT_JAR := $(TOOLS_OUT_DIR)/IconToolkit.jar
RCEDIT_TOOL ?=

# Java std library project (Gradle)
JAVA_LIB_DIR := $(ROOT_DIR)/libs/std/java
JAVA_LIB_OUT_DIR := $(BUILD_DIR_ABS)/libs/java
JAVA_RUNTIME_OUT_DIR := $(BUILD_DIR_ABS)/runtime/java
JAVA_STD_DB_VERSION ?= 8
JAVA_STD_DB_FILE := $(JAVA_LIB_OUT_DIR)/jdk$(JAVA_STD_DB_VERSION)-stdlib.db

# Native std/base project (Makefile)
NATIVE_LIB_DIR := $(ROOT_DIR)/libs/std/native
NATIVE_LIB_BUILD_DIR := $(NATIVE_LIB_DIR)/build
NATIVE_LIB_OUT_DIR := $(BUILD_DIR_ABS)/libs/native
NATIVE_RUNTIME_OUT_DIR := $(BUILD_DIR_ABS)/runtime/native
NATIVE_BASE_TARGET := libxlang-core
NATIVE_STD_TARGET := libxlang-std
NATIVE_BASE_STATIC_LIB := $(NATIVE_BASE_TARGET).a
NATIVE_STD_STATIC_LIB := $(NATIVE_STD_TARGET).a
RUNTIME_CORE_DIR := $(ROOT_DIR)/runtime/core
RUNTIME_CORE_BUILD_DIR := $(RUNTIME_CORE_DIR)/build
RUNTIME_GC_DIR := $(ROOT_DIR)/runtime/gc
RUNTIME_GC_BUILD_DIR := $(RUNTIME_GC_DIR)/build
RUNTIME_EXCEPTION_DIR := $(ROOT_DIR)/runtime/exception
RUNTIME_EXCEPTION_BUILD_DIR := $(RUNTIME_EXCEPTION_DIR)/build
NATIVE_SYSLIB_OUT_DIR := $(BUILD_DIR_ABS)/native
NATIVE_SYSLIB_NAMES := libkernel32.a libmsvcrt.a libmingw32.a libmingwex.a libwinpthread.a libgcc.a libgcc_eh.a
UNAME_S := $(shell uname -s 2>/dev/null || echo unknown)
ifeq ($(OS),Windows_NT)
NATIVE_SHARED_EXT := dll
NATIVE_BASE_LINK_LIB := $(NATIVE_BASE_TARGET).dll.a
NATIVE_STD_LINK_LIB := $(NATIVE_STD_TARGET).dll.a
else ifneq (,$(findstring MINGW,$(UNAME_S)))
NATIVE_SHARED_EXT := dll
NATIVE_BASE_LINK_LIB := $(NATIVE_BASE_TARGET).dll.a
NATIVE_STD_LINK_LIB := $(NATIVE_STD_TARGET).dll.a
else ifneq (,$(findstring MSYS,$(UNAME_S)))
NATIVE_SHARED_EXT := dll
NATIVE_BASE_LINK_LIB := $(NATIVE_BASE_TARGET).dll.a
NATIVE_STD_LINK_LIB := $(NATIVE_STD_TARGET).dll.a
else ifneq (,$(findstring CYGWIN,$(UNAME_S)))
NATIVE_SHARED_EXT := dll
NATIVE_BASE_LINK_LIB := $(NATIVE_BASE_TARGET).dll.a
NATIVE_STD_LINK_LIB := $(NATIVE_STD_TARGET).dll.a
else
ifeq ($(UNAME_S),Darwin)
NATIVE_SHARED_EXT := dylib
else
NATIVE_SHARED_EXT := so
endif
NATIVE_BASE_LINK_LIB := $(NATIVE_BASE_TARGET).a
NATIVE_STD_LINK_LIB := $(NATIVE_STD_TARGET).a
endif

# Keep Gradle caches local to avoid global cache issues
GRADLE_USER_HOME := $(BUILD_DIR_ABS)/.gradle-home
GRADLE_ARGS := --console=plain --no-daemon

# On Unix-like systems, normalize gradlew line endings before execution
# to avoid /bin/sh^M failures when scripts were checked out with CRLF.
define PREPARE_GRADLEW_CMD
	chmod +x ./gradlew; if command -v perl >/dev/null 2>&1; then perl -i -pe 's/\r\n/\n/g' ./gradlew; fi
endef

.PHONY: help all build all_components full compiler move_native runtime_core runtime_gc runtime_exception runtime_ext java_std native_std compile update maybe_update bytecode_tool tools java_lib native_lib stage_syslibs \
	install install_all install_bin install_tools install_java_lib install_native_lib uninstall \
	clean clean_ide rebuild distclean

help:
	@echo "Usage: ./configure [opts] && make -jN [target] && make install"
	@echo ""
	@echo "Targets:"
	@echo "  all/build       Build default pipeline (compiler -> move_native -> runtime core -> runtime gc/exception -> native std -> tools)"
	@echo "  compiler        Build xlang compiler executable"
	@echo "  move_native     Stage native syslibs into build/native (Windows; needs --gcc-lib)"
	@echo "  runtime_core    Build runtime/core and stage runtime base libs"
	@echo "  runtime_gc      Build runtime/gc (depends on runtime_core)"
	@echo "  runtime_exception Build runtime/exception (depends on runtime_core)"
	@echo "  runtime_ext     Build runtime gc + exception"
	@echo "  java_std        Build libs/std/java artifacts and move to build output"
	@echo "  native_std      Build libs/std/native artifacts and move to build/libs/native"
	@echo "  all_components  Alias of all"
	@echo "  full            Alias of all_components"
	@echo "  compile         Build xlang executable"
	@echo "  update      Run cabal update in compiler/"
	@echo "  tools       Build BytecodeToolkit + IconToolkit jars (Windows: patch xlang.exe icon from images/icon.svg)"
	@echo "  java_lib    Build libs/std/java artifacts"
	@echo "  native_lib  Build libs/std/native (depends on runtime libs; outputs to build/libs/native)"
	@echo "  install         Install all components"
	@echo "  install_all     Install xlang + tools + java std + native std/base under \$$DESTDIR\$$XLANG_LIBDIR"
	@echo "  uninstall       Remove installed xlang and xlang lib dir"
	@echo "  clean           Clean build artifacts"
	@echo "  distclean       clean + remove generated config.mk"
	@echo "  clean_ide       Remove .vscode/.idea folders"
	@echo "  rebuild         clean + all"
	@echo ""
	@echo "Standard flow:"
	@echo "  ./configure --prefix=/usr/local"
	@echo "  make -j24"
	@echo "  make install"
	@echo ""
	@echo "Optional full build:"
	@echo "  make -j24 all"
	@echo "  make -j24 all_components"
	@echo "  make install_all"

all: tools

# Alias for people who prefer `make build`
build: all

compiler: compile

move_native: compiler stage_syslibs

runtime_core: move_native
	mkdir -p "$(RUNTIME_CORE_BUILD_DIR)"
	cd "$(RUNTIME_CORE_BUILD_DIR)" && sh ../configure --build-dir=. --target="$(NATIVE_BASE_TARGET)"
	$(MAKE) -C "$(RUNTIME_CORE_BUILD_DIR)" clean
	$(MAKE) -C "$(RUNTIME_CORE_BUILD_DIR)"
	mkdir -p "$(NATIVE_LIB_OUT_DIR)" "$(NATIVE_RUNTIME_OUT_DIR)"
	rm -f "$(NATIVE_LIB_OUT_DIR)/libxlang-base.a" "$(NATIVE_LIB_OUT_DIR)/libxlang-base.dll.a" 2>/dev/null || true
	rm -f "$(NATIVE_RUNTIME_OUT_DIR)/libxlang-base.dll" "$(NATIVE_RUNTIME_OUT_DIR)/libxlang-base.so" "$(NATIVE_RUNTIME_OUT_DIR)/libxlang-base.dylib" 2>/dev/null || true
	cp -f "$(RUNTIME_CORE_BUILD_DIR)/libs/$(NATIVE_BASE_TARGET).$(NATIVE_SHARED_EXT)" "$(NATIVE_RUNTIME_OUT_DIR)/" 2>/dev/null || true
	cp -f "$(RUNTIME_CORE_BUILD_DIR)/libs/$(NATIVE_BASE_LINK_LIB)" "$(NATIVE_LIB_OUT_DIR)/" 2>/dev/null || true
	cp -f "$(RUNTIME_CORE_BUILD_DIR)/libs/$(NATIVE_BASE_STATIC_LIB)" "$(NATIVE_LIB_OUT_DIR)/" 2>/dev/null || true

runtime_gc: runtime_core
	@set -e; \
	module_dir="$(RUNTIME_GC_DIR)"; \
	module_build="$(RUNTIME_GC_BUILD_DIR)"; \
	if [ -f "$$module_dir/configure" ]; then \
		mkdir -p "$$module_build"; \
		cd "$$module_build" && sh ../configure --build-dir=.; \
	fi; \
	if [ -f "$$module_build/Makefile" ]; then \
		$(MAKE) -C "$$module_build" clean; \
		$(MAKE) -C "$$module_build"; \
	elif [ -f "$$module_dir/Makefile" ]; then \
		$(MAKE) -C "$$module_dir" clean; \
		$(MAKE) -C "$$module_dir"; \
	else \
		echo "[INFO] runtime/gc has no Makefile/configure, skip build"; \
	fi; \
	mkdir -p "$(NATIVE_LIB_OUT_DIR)" "$(NATIVE_RUNTIME_OUT_DIR)"; \
	for from in "$$module_build/libs" "$$module_dir/libs"; do \
		[ -d "$$from" ] || continue; \
		for f in "$$from"/*.a "$$from"/*.dll.a; do [ -f "$$f" ] && cp -f "$$f" "$(NATIVE_LIB_OUT_DIR)/"; done; \
		for f in "$$from"/*.$(NATIVE_SHARED_EXT); do [ -f "$$f" ] && cp -f "$$f" "$(NATIVE_RUNTIME_OUT_DIR)/"; done; \
	done

runtime_exception: runtime_core
	@set -e; \
	module_dir="$(RUNTIME_EXCEPTION_DIR)"; \
	module_build="$(RUNTIME_EXCEPTION_BUILD_DIR)"; \
	if [ -f "$$module_dir/configure" ]; then \
		mkdir -p "$$module_build"; \
		cd "$$module_build" && sh ../configure --build-dir=.; \
	fi; \
	if [ -f "$$module_build/Makefile" ]; then \
		$(MAKE) -C "$$module_build" clean; \
		$(MAKE) -C "$$module_build"; \
	elif [ -f "$$module_dir/Makefile" ]; then \
		$(MAKE) -C "$$module_dir" clean; \
		$(MAKE) -C "$$module_dir"; \
	else \
		echo "[INFO] runtime/exception has no Makefile/configure, skip build"; \
	fi; \
	mkdir -p "$(NATIVE_LIB_OUT_DIR)" "$(NATIVE_RUNTIME_OUT_DIR)"; \
	for from in "$$module_build/libs" "$$module_dir/libs"; do \
		[ -d "$$from" ] || continue; \
		for f in "$$from"/*.a "$$from"/*.dll.a; do [ -f "$$f" ] && cp -f "$$f" "$(NATIVE_LIB_OUT_DIR)/"; done; \
		for f in "$$from"/*.$(NATIVE_SHARED_EXT); do [ -f "$$f" ] && cp -f "$$f" "$(NATIVE_RUNTIME_OUT_DIR)/"; done; \
	done

runtime_ext: runtime_gc runtime_exception

java_std: java_lib

native_std: native_lib

all_components: all

full: all_components

update:
	cd "$(COMPILER_DIR)" && $(CABAL) update

maybe_update:
ifeq ($(CABAL_UPDATE),1)
	$(MAKE) update
else
	@true
endif

compile: maybe_update
	mkdir -p "$(BUILD_DIR_ABS)"
	cd "$(COMPILER_DIR)" && $(CABAL) build -j$(JOBS) exe:$(EXE)
	EXE_PATH=$$(cd "$(COMPILER_DIR)" && $(CABAL) list-bin exe:$(EXE)); \
		cp -f "$$EXE_PATH" "$(EXE_OUT)"

bytecode_tool:
	mkdir -p "$(TOOLS_OUT_DIR)"
	@if [ "$(OS)" != "Windows_NT" ]; then \
		cd "$(BYTECODEGEN_DIR)" && $(PREPARE_GRADLEW_CMD); \
	else \
		cd "$(BYTECODEGEN_DIR)" && chmod +x ./gradlew; \
	fi
	cd "$(BYTECODEGEN_DIR)" && GRADLE_USER_HOME="$(GRADLE_USER_HOME)" ./gradlew build -PxlangJobs=$(JOBS) $(GRADLE_ARGS)
	cp -f "$(BYTECODEGEN_DIR)"/build/libs/BytecodeToolkit.jar "$(TOOLS_OUT_DIR)/BytecodeToolkit.jar"
	@if [ ! -f "$(TOOLS_OUT_DIR)/BytecodeToolkit.jar" ]; then \
		echo "[ERROR] missing BytecodeToolkit.jar: $(TOOLS_OUT_DIR)/BytecodeToolkit.jar"; \
		exit 1; \
	fi

tools: native_std bytecode_tool
	mkdir -p "$(TOOLS_OUT_DIR)"
	@if [ "$(OS)" != "Windows_NT" ]; then \
		cd "$(ICONTOOLKIT_DIR)" && $(PREPARE_GRADLEW_CMD); \
	else \
		cd "$(ICONTOOLKIT_DIR)" && chmod +x ./gradlew; \
	fi
	cd "$(ICONTOOLKIT_DIR)" && GRADLE_USER_HOME="$(GRADLE_USER_HOME)" ./gradlew build -PxlangJobs=$(JOBS) $(GRADLE_ARGS)
	cp -f "$(ICONTOOLKIT_DIR)"/build/libs/*.jar "$(TOOLS_OUT_DIR)/" 2>/dev/null || true
	@if [ "$(OS)" = "Windows_NT" ]; then \
		if [ ! -f "$(ICONTOOLKIT_JAR)" ]; then \
			echo "[ERROR] missing IconToolkit.jar: $(ICONTOOLKIT_JAR)"; \
			exit 1; \
		fi; \
		if [ ! -f "$(ICON_SVG)" ]; then \
			echo "[WARN] skip xlang.exe icon patch, SVG not found: $(ICON_SVG)"; \
		elif [ ! -f "$(EXE_OUT)" ]; then \
			echo "[WARN] skip xlang.exe icon patch, EXE not found: $(EXE_OUT)"; \
		else \
			echo "[INFO] patching xlang.exe icon from $(ICON_SVG)"; \
			if [ -n "$(RCEDIT_TOOL)" ]; then \
				java -jar "$(ICONTOOLKIT_JAR)" --tool="$(RCEDIT_TOOL)" -s "$(ICON_SVG)" -t "$(EXE_OUT)"; \
			else \
				java -jar "$(ICONTOOLKIT_JAR)" -s "$(ICON_SVG)" -t "$(EXE_OUT)"; \
			fi; \
		fi; \
	fi

java_lib: compile bytecode_tool
	mkdir -p "$(JAVA_LIB_OUT_DIR)" "$(JAVA_RUNTIME_OUT_DIR)"
	@if [ "$(OS)" != "Windows_NT" ]; then \
		cd "$(JAVA_LIB_DIR)" && $(PREPARE_GRADLEW_CMD); \
	else \
		cd "$(JAVA_LIB_DIR)" && chmod +x ./gradlew; \
	fi
	cd "$(JAVA_LIB_DIR)" && GRADLE_USER_HOME="$(GRADLE_USER_HOME)" ./gradlew build -PxlangJobs=$(XLANG_JOBS) -PxlangExe="$(EXE_OUT_GRADLE)" $(GRADLE_ARGS)
	rm -f "$(JAVA_LIB_DIR)/build/libs/xlang-stdlib-alpha.jar" 2>/dev/null || true
	rm -f "$(JAVA_LIB_DIR)/build/libs/xlang-stdlib.zip" 2>/dev/null || true
	rm -f "$(JAVA_LIB_OUT_DIR)/xlang-stdlib-alpha.jar" "$(JAVA_LIB_OUT_DIR)/xlang-stdlib.zip" 2>/dev/null || true
	cp -f "$(JAVA_LIB_DIR)/build/libs/xlang-stdlib.jar" "$(JAVA_LIB_OUT_DIR)/" 2>/dev/null || true
	cp -f "$(JAVA_LIB_DIR)"/build/runtime-libs/*.jar "$(JAVA_RUNTIME_OUT_DIR)/" 2>/dev/null || true
	@if [ ! -f "$(JAVA_LIB_OUT_DIR)/xlang-stdlib.jar" ]; then \
		echo "[ERROR] missing stdlib jar: $(JAVA_LIB_OUT_DIR)/xlang-stdlib.jar"; \
		exit 1; \
	fi
	@if command -v jar >/dev/null 2>&1; then \
		jar tf "$(JAVA_LIB_OUT_DIR)/xlang-stdlib.jar" | grep -q "xlang/io/Console.class" || { \
			echo "[ERROR] stdlib jar missing xlang/io/Console.class"; exit 1; }; \
		jar tf "$(JAVA_LIB_OUT_DIR)/xlang-stdlib.jar" | grep -q "xlang/Math.class" || { \
			echo "[ERROR] stdlib jar missing xlang/Math.class"; exit 1; }; \
	else \
		echo "[WARN] 'jar' tool not found; skip stdlib content verification"; \
	fi
	@if [ ! -f "$(JAVA_STD_DB_FILE)" ]; then \
		echo "[INFO] jdk std metadata missing, download jdk$(JAVA_STD_DB_VERSION)-stdlib.db"; \
		"$(EXE_OUT)" -download=$(JAVA_STD_DB_VERSION); \
	fi

native_lib: runtime_ext compile
	mkdir -p "$(NATIVE_LIB_BUILD_DIR)"
	cd "$(NATIVE_LIB_BUILD_DIR)" && sh ../configure --build-dir=. --target="$(NATIVE_STD_TARGET)"
	$(MAKE) -C "$(NATIVE_LIB_BUILD_DIR)" clean
	$(MAKE) -C "$(NATIVE_LIB_BUILD_DIR)" RUNTIME_CORE_BUILD_DIR="$(RUNTIME_CORE_BUILD_DIR)"
	mkdir -p "$(NATIVE_LIB_OUT_DIR)" "$(NATIVE_RUNTIME_OUT_DIR)"
	cp -f "$(NATIVE_LIB_BUILD_DIR)/libs/$(NATIVE_STD_TARGET).$(NATIVE_SHARED_EXT)" "$(NATIVE_RUNTIME_OUT_DIR)/" 2>/dev/null || true
	cp -f "$(NATIVE_LIB_BUILD_DIR)/libs/$(NATIVE_STD_LINK_LIB)" "$(NATIVE_LIB_OUT_DIR)/" 2>/dev/null || true
	cp -f "$(NATIVE_LIB_BUILD_DIR)/libs/$(NATIVE_STD_STATIC_LIB)" "$(NATIVE_LIB_OUT_DIR)/" 2>/dev/null || true

stage_syslibs:
ifeq ($(NATIVE_SHARED_EXT),dll)
	@if [ -n "$(GCC_LIB)" ] && [ -d "$(GCC_LIB)" ]; then \
		mkdir -p "$(NATIVE_SYSLIB_OUT_DIR)"; \
		target_triple="$${NATIVE_GCC_TRIPLE:-x86_64-w64-mingw32}"; \
		gcc_dirs="$(GCC_LIB)"; \
		if [ -d "$(GCC_LIB)/../lib/gcc" ]; then \
			for d in "$(GCC_LIB)"/../lib/gcc/*/*; do \
				case "$$d" in */lib/gcc/$$target_triple/*) if [ -d "$$d" ]; then gcc_dirs="$$gcc_dirs $$d"; fi ;; esac; \
			done; \
		fi; \
		for n in $(NATIVE_SYSLIB_NAMES); do \
			found=0; \
			for d in $$gcc_dirs; do \
				if [ -f "$$d/$$n" ]; then \
					cp -f "$$d/$$n" "$(NATIVE_SYSLIB_OUT_DIR)/"; \
					found=1; \
					break; \
				fi; \
			done; \
			if [ $$found -eq 0 ]; then \
				echo "[WARN] missing syslib in GCC_LIB: $$n"; \
			fi; \
		done; \
	else \
		echo "[INFO] skip syslib staging (set --gcc-lib=<path> to enable)"; \
	fi
else
	@true
endif

install: install_all

install_all: install_bin install_tools install_java_lib install_native_lib

install_bin: compile
	mkdir -p "$(DESTDIR)$(BINDIR)"
	$(INSTALL_PROGRAM) "$(EXE_OUT)" "$(DESTDIR)$(BINDIR)/$(EXE_FILE)"

install_tools: tools
	mkdir -p "$(DESTDIR)$(XLANG_LIBDIR)/tools"
	set -e; \
	for f in "$(TOOLS_OUT_DIR)"/*.jar; do \
		[ -f "$$f" ] || continue; \
		$(INSTALL_DATA) "$$f" "$(DESTDIR)$(XLANG_LIBDIR)/tools/"; \
	done

install_java_lib: java_lib
	mkdir -p "$(DESTDIR)$(XLANG_LIBDIR)/libs/java" "$(DESTDIR)$(XLANG_LIBDIR)/runtime/java"
	set -e; \
	for f in "$(JAVA_LIB_OUT_DIR)"/*; do \
		[ -f "$$f" ] || continue; \
		$(INSTALL_DATA) "$$f" "$(DESTDIR)$(XLANG_LIBDIR)/libs/java/"; \
	done; \
	for f in "$(JAVA_RUNTIME_OUT_DIR)"/*; do \
		[ -f "$$f" ] || continue; \
		$(INSTALL_DATA) "$$f" "$(DESTDIR)$(XLANG_LIBDIR)/runtime/java/"; \
	done

install_native_lib: stage_syslibs native_lib
	mkdir -p "$(DESTDIR)$(XLANG_LIBDIR)/libs/native" "$(DESTDIR)$(XLANG_LIBDIR)/runtime/native" "$(DESTDIR)$(XLANG_LIBDIR)/native"
	set -e; \
	for f in "$(NATIVE_LIB_OUT_DIR)"/*; do \
		[ -f "$$f" ] || continue; \
		$(INSTALL_DATA) "$$f" "$(DESTDIR)$(XLANG_LIBDIR)/libs/native/"; \
	done; \
	for f in "$(NATIVE_RUNTIME_OUT_DIR)"/*; do \
		[ -f "$$f" ] || continue; \
		$(INSTALL_DATA) "$$f" "$(DESTDIR)$(XLANG_LIBDIR)/runtime/native/"; \
	done; \
	for f in "$(NATIVE_SYSLIB_OUT_DIR)"/*.a; do \
		[ -f "$$f" ] || continue; \
		$(INSTALL_DATA) "$$f" "$(DESTDIR)$(XLANG_LIBDIR)/native/"; \
	done

uninstall:
	rm -f "$(DESTDIR)$(BINDIR)/$(EXE_FILE)" "$(DESTDIR)$(BINDIR)/$(EXE)"
	if [ -n "$(XLANG_LIBDIR)" ]; then rm -rf "$(DESTDIR)$(XLANG_LIBDIR)"; fi

clean:
	cd "$(COMPILER_DIR)" && $(CABAL) clean
	rm -rf "$(COMPILER_DIR)/.vscode" 2>/dev/null || true
	@if [ "$(OS)" != "Windows_NT" ]; then \
		cd "$(BYTECODEGEN_DIR)" && $(PREPARE_GRADLEW_CMD); \
		cd "$(ICONTOOLKIT_DIR)" && $(PREPARE_GRADLEW_CMD); \
		cd "$(JAVA_LIB_DIR)" && $(PREPARE_GRADLEW_CMD); \
	else \
		cd "$(BYTECODEGEN_DIR)" && chmod +x ./gradlew; \
		cd "$(ICONTOOLKIT_DIR)" && chmod +x ./gradlew; \
		cd "$(JAVA_LIB_DIR)" && chmod +x ./gradlew; \
	fi
	cd "$(BYTECODEGEN_DIR)" && (GRADLE_USER_HOME="$(GRADLE_USER_HOME)" ./gradlew --stop $(GRADLE_ARGS) || true)
	cd "$(ICONTOOLKIT_DIR)" && (GRADLE_USER_HOME="$(GRADLE_USER_HOME)" ./gradlew --stop $(GRADLE_ARGS) || true)
	cd "$(JAVA_LIB_DIR)" && (GRADLE_USER_HOME="$(GRADLE_USER_HOME)" ./gradlew --stop $(GRADLE_ARGS) || true)
	cd "$(BYTECODEGEN_DIR)" && (GRADLE_USER_HOME="$(GRADLE_USER_HOME)" ./gradlew clean $(GRADLE_ARGS) || true)
	cd "$(ICONTOOLKIT_DIR)" && (GRADLE_USER_HOME="$(GRADLE_USER_HOME)" ./gradlew clean $(GRADLE_ARGS) || true)
	cd "$(JAVA_LIB_DIR)" && (GRADLE_USER_HOME="$(GRADLE_USER_HOME)" ./gradlew clean $(GRADLE_ARGS) || true)
	rm -rf "$(BYTECODEGEN_DIR)/.gradle" "$(BYTECODEGEN_DIR)/.idea" "$(BYTECODEGEN_DIR)/.kotlin" "$(BYTECODEGEN_DIR)/bin" "$(BYTECODEGEN_DIR)/build" 2>/dev/null || true
	rm -rf "$(ICONTOOLKIT_DIR)/.gradle" "$(ICONTOOLKIT_DIR)/.idea" "$(ICONTOOLKIT_DIR)/.kotlin" "$(ICONTOOLKIT_DIR)/bin" "$(ICONTOOLKIT_DIR)/build" 2>/dev/null || true
	rm -rf "$(JAVA_LIB_DIR)/.gradle" "$(JAVA_LIB_DIR)/.idea" "$(JAVA_LIB_DIR)/.kotlin" "$(JAVA_LIB_DIR)/bin" "$(JAVA_LIB_DIR)/build" 2>/dev/null || true
	rm -rf "$(NATIVE_LIB_DIR)/.vscode" "$(NATIVE_LIB_DIR)/.idea" "$(NATIVE_LIB_BUILD_DIR)" 2>/dev/null || true
	rm -rf "$(RUNTIME_CORE_BUILD_DIR)" "$(RUNTIME_CORE_DIR)/.vscode" "$(RUNTIME_CORE_DIR)/.idea" 2>/dev/null || true
	rm -rf "$(RUNTIME_GC_BUILD_DIR)" "$(RUNTIME_GC_DIR)/.vscode" "$(RUNTIME_GC_DIR)/.idea" 2>/dev/null || true
	rm -rf "$(RUNTIME_EXCEPTION_BUILD_DIR)" "$(RUNTIME_EXCEPTION_DIR)/.vscode" "$(RUNTIME_EXCEPTION_DIR)/.idea" 2>/dev/null || true
	rm -rf "$(GRADLE_USER_HOME)/caches" || true
	rm -rf "$(BUILD_DIR_ABS)/tools" "$(BUILD_DIR_ABS)/libs" "$(BUILD_DIR_ABS)/runtime" "$(BUILD_DIR_ABS)/std" "$(BUILD_DIR_ABS)/native" "$(BUILD_DIR_ABS)/native-libs" "$(BUILD_DIR_ABS)/$(EXE_FILE)" "$(BUILD_DIR_ABS)/$(EXE)" "$(BUILD_DIR_ABS)"/*.exe 2>/dev/null || true
	$(MAKE) clean_ide

clean_ide:
	rm -rf "$(ROOT_DIR)/.vscode" "$(ROOT_DIR)/.idea" 2>/dev/null || true
	rm -rf "$(COMPILER_DIR)/.vscode" "$(COMPILER_DIR)/.idea" 2>/dev/null || true
	rm -rf "$(BYTECODEGEN_DIR)/.vscode" "$(BYTECODEGEN_DIR)/.idea" 2>/dev/null || true
	rm -rf "$(ICONTOOLKIT_DIR)/.vscode" "$(ICONTOOLKIT_DIR)/.idea" 2>/dev/null || true
	rm -rf "$(JAVA_LIB_DIR)/.vscode" "$(JAVA_LIB_DIR)/.idea" 2>/dev/null || true
	rm -rf "$(NATIVE_LIB_DIR)/.vscode" "$(NATIVE_LIB_DIR)/.idea" 2>/dev/null || true
	rm -rf "$(RUNTIME_CORE_DIR)/.vscode" "$(RUNTIME_CORE_DIR)/.idea" 2>/dev/null || true
	rm -rf "$(RUNTIME_GC_DIR)/.vscode" "$(RUNTIME_GC_DIR)/.idea" 2>/dev/null || true
	rm -rf "$(RUNTIME_EXCEPTION_DIR)/.vscode" "$(RUNTIME_EXCEPTION_DIR)/.idea" 2>/dev/null || true

rebuild: clean all

distclean: clean
	rm -f "$(CONFIG_MK)"
