SHELL := /bin/sh

.DEFAULT_GOAL := all

# Root directory (this Makefile is expected at repo root)
ROOT_DIR := $(abspath .)

# Optional config generated by ./configure
CONFIG_MK ?= config.mk
-include $(CONFIG_MK)

# Build output directory (override: make BUILD_DIR=out)
BUILD_DIR ?= build
BUILD_DIR_ABS := $(ROOT_DIR)/$(BUILD_DIR)

# Install directories (override in config.mk or make variables)
PREFIX ?= /usr/local
EXEC_PREFIX ?= $(PREFIX)
BINDIR ?= $(EXEC_PREFIX)/bin
LIBDIR ?= $(EXEC_PREFIX)/lib
XLANG_LIBDIR ?= $(LIBDIR)/xlang
INSTALL ?= install
INSTALL_PROGRAM ?= $(INSTALL) -m 0755
INSTALL_DATA ?= $(INSTALL) -m 0644

# Parse make parallel flag, e.g. `make -j8` or `make --jobs=8`
MAKE_JOBS_LONG := $(patsubst --jobs=%,%,$(filter --jobs=%,$(MAKEFLAGS)))
MAKE_JOBS_SHORT := $(patsubst -j%,%,$(filter -j%,$(MAKEFLAGS)))
MAKE_JOBS := $(firstword $(filter-out ,$(MAKE_JOBS_LONG) $(MAKE_JOBS_SHORT)))

# Parallel jobs (default: from make -j, otherwise CPU count)
JOBS ?= $(if $(MAKE_JOBS),$(MAKE_JOBS),$(shell (command -v nproc >/dev/null 2>&1 && nproc) || (getconf _NPROCESSORS_ONLN 2>/dev/null) || echo 8))

# Optional pre-build metadata refresh.
# Use: make CABAL_UPDATE=1 all
CABAL_UPDATE ?= 0
CABAL ?= cabal

# xlang std compile jobs for libs/java
# override explicitly if needed: make java_lib XLANG_JOBS=9
XLANG_JOBS ?= $(JOBS)

# Haskell compiler (Cabal)
COMPILER_DIR := $(ROOT_DIR)/compiler
EXE := xlang
EXE_OUT := $(BUILD_DIR_ABS)/$(EXE)

# Java tool (Gradle)
BYTECODEGEN_DIR := $(ROOT_DIR)/tools/BytecodeToolkit
TOOLS_OUT_DIR := $(BUILD_DIR_ABS)/tools

# Java library project (Gradle)
JAVA_LIB_DIR := $(ROOT_DIR)/libs/java
JAVA_LIB_OUT_DIR := $(BUILD_DIR_ABS)/libs/java

# Keep Gradle caches local to avoid global cache issues
GRADLE_USER_HOME := $(BUILD_DIR_ABS)/.gradle-home
GRADLE_ARGS := --console=plain --no-daemon

.PHONY: help all build all_components full compile update maybe_update tools java_lib \
	install install_all install_bin install_tools install_java_lib uninstall \
	clean clean_ide rebuild distclean

help:
	@echo "Usage: ./configure [opts] && make -jN [target] && make install"
	@echo ""
	@echo "Targets:"
	@echo "  all/build       Build xlang executable (default)"
	@echo "  all_components  Build compiler + tools + java_lib"
	@echo "  full            Alias of all_components"
	@echo "  compile         Build xlang executable"
	@echo "  update      Run cabal update in compiler/"
	@echo "  tools       Build BytecodeToolkit jars"
	@echo "  java_lib    Build libs/java artifacts"
	@echo "  install         Install xlang to \$$DESTDIR\$$BINDIR"
	@echo "  install_all     Install xlang + jars under \$$DESTDIR\$$XLANG_LIBDIR"
	@echo "  uninstall       Remove installed xlang and xlang lib dir"
	@echo "  clean           Clean build artifacts"
	@echo "  distclean       clean + remove generated config.mk"
	@echo "  clean_ide       Remove .vscode/.idea folders"
	@echo "  rebuild         clean + all"
	@echo ""
	@echo "Standard flow:"
	@echo "  ./configure --prefix=/usr/local"
	@echo "  make -j24"
	@echo "  make install"
	@echo ""
	@echo "Optional full build:"
	@echo "  make -j24 all_components"
	@echo "  make install_all"

all: compile

# Alias for people who prefer `make build`
build: all

all_components: compile tools java_lib

full: all_components

update:
	cd "$(COMPILER_DIR)" && $(CABAL) update

maybe_update:
ifeq ($(CABAL_UPDATE),1)
	$(MAKE) update
else
	@true
endif

compile: maybe_update
	mkdir -p "$(BUILD_DIR_ABS)"
	cd "$(COMPILER_DIR)" && $(CABAL) build -j$(JOBS) exe:$(EXE)
	EXE_PATH=$$(cd "$(COMPILER_DIR)" && $(CABAL) list-bin exe:$(EXE)); \
		cp -f "$$EXE_PATH" "$(BUILD_DIR_ABS)/"

tools:
	mkdir -p "$(TOOLS_OUT_DIR)"
	cd "$(BYTECODEGEN_DIR)" && chmod +x ./gradlew
	cd "$(BYTECODEGEN_DIR)" && GRADLE_USER_HOME="$(GRADLE_USER_HOME)" ./gradlew build -PxlangJobs=$(JOBS) $(GRADLE_ARGS)
	cp -f "$(BYTECODEGEN_DIR)"/build/libs/*.jar "$(TOOLS_OUT_DIR)/" 2>/dev/null || true

java_lib: compile
	mkdir -p "$(JAVA_LIB_OUT_DIR)"
	cd "$(JAVA_LIB_DIR)" && chmod +x ./gradlew
	cd "$(JAVA_LIB_DIR)" && GRADLE_USER_HOME="$(GRADLE_USER_HOME)" ./gradlew build -PxlangJobs=$(XLANG_JOBS) -PxlangExe="$(EXE_OUT)" $(GRADLE_ARGS)
	cp -f "$(JAVA_LIB_DIR)"/build/libs/* "$(JAVA_LIB_OUT_DIR)/" 2>/dev/null || true
	cp -f "$(JAVA_LIB_DIR)"/build/runtime-libs/*.jar "$(JAVA_LIB_OUT_DIR)/" 2>/dev/null || true

install: install_bin

install_all: install_bin install_tools install_java_lib

install_bin: compile
	mkdir -p "$(DESTDIR)$(BINDIR)"
	$(INSTALL_PROGRAM) "$(EXE_OUT)" "$(DESTDIR)$(BINDIR)/$(EXE)"

install_tools: tools
	mkdir -p "$(DESTDIR)$(XLANG_LIBDIR)/tools"
	set -e; \
	for f in "$(TOOLS_OUT_DIR)"/*.jar; do \
		[ -f "$$f" ] || continue; \
		$(INSTALL_DATA) "$$f" "$(DESTDIR)$(XLANG_LIBDIR)/tools/"; \
	done

install_java_lib: java_lib
	mkdir -p "$(DESTDIR)$(XLANG_LIBDIR)/java"
	set -e; \
	for f in "$(JAVA_LIB_OUT_DIR)"/*; do \
		[ -f "$$f" ] || continue; \
		$(INSTALL_DATA) "$$f" "$(DESTDIR)$(XLANG_LIBDIR)/java/"; \
	done

uninstall:
	rm -f "$(DESTDIR)$(BINDIR)/$(EXE)"
	if [ -n "$(XLANG_LIBDIR)" ]; then rm -rf "$(DESTDIR)$(XLANG_LIBDIR)"; fi

clean:
	cd "$(COMPILER_DIR)" && $(CABAL) clean
	cd "$(BYTECODEGEN_DIR)" && (GRADLE_USER_HOME="$(GRADLE_USER_HOME)" ./gradlew --stop $(GRADLE_ARGS) || true)
	cd "$(JAVA_LIB_DIR)" && (GRADLE_USER_HOME="$(GRADLE_USER_HOME)" ./gradlew --stop $(GRADLE_ARGS) || true)
	cd "$(BYTECODEGEN_DIR)" && (GRADLE_USER_HOME="$(GRADLE_USER_HOME)" ./gradlew clean $(GRADLE_ARGS) || true)
	cd "$(JAVA_LIB_DIR)" && (GRADLE_USER_HOME="$(GRADLE_USER_HOME)" ./gradlew clean $(GRADLE_ARGS) || true)
	rm -rf "$(GRADLE_USER_HOME)/caches" || true
	rm -rf "$(BUILD_DIR_ABS)/tools" "$(BUILD_DIR_ABS)/libs" "$(BUILD_DIR_ABS)/$(EXE)" "$(BUILD_DIR_ABS)"/*.exe 2>/dev/null || true
	$(MAKE) clean_ide

clean_ide:
	rm -rf "$(ROOT_DIR)/.vscode" "$(ROOT_DIR)/.idea" 2>/dev/null || true
	rm -rf "$(COMPILER_DIR)/.vscode" "$(COMPILER_DIR)/.idea" 2>/dev/null || true
	rm -rf "$(BYTECODEGEN_DIR)/.vscode" "$(BYTECODEGEN_DIR)/.idea" 2>/dev/null || true
	rm -rf "$(JAVA_LIB_DIR)/.vscode" "$(JAVA_LIB_DIR)/.idea" 2>/dev/null || true

rebuild: clean all

distclean: clean
	rm -f "$(CONFIG_MK)"
