name:                 compiler
version:              0.1.0.0
visibility:           public
id:                   compiler-0.1.0.0-inplace
key:                  compiler-0.1.0.0-inplace
license:              MIT
maintainer:           dw725@ic.ac.uk
author:               Wang Di
abi:                  inplace
exposed:              True
exposed-modules:
    CompileJava IR.Lowing IR.Optimize IR.TAC IR.TACLowing Lex.Token
    Lex.TokenPass Lex.Tokenizer Lowing.JVM Lowing.JVMJson
    Lowing.JVMLowing Parse.ParseBlock Parse.ParseExpr Parse.ParseProgm
    Parse.ParseStmt Parse.ParserBasic Parse.SyntaxTree
    Semantic.CheckProgram Semantic.ContextCheck Semantic.LibLoader
    Semantic.NameEnv Semantic.OpInfer Semantic.ReturnCheck
    Semantic.SemanticDebug Semantic.TypeCheck Semantic.TypeEnv
    Util.Basic Util.Exception Util.FileHelper Util.Type Xlang

import-dirs:
    D:\Coding\projects\Mixed\xlang\compiler\dist-newstyle\build\x86_64-windows\ghc-9.4.8\compiler-0.1.0.0\opt\build

library-dirs:
    D:\Coding\projects\Mixed\xlang\compiler\dist-newstyle\build\x86_64-windows\ghc-9.4.8\compiler-0.1.0.0\opt\build

library-dirs-static:
    D:\Coding\projects\Mixed\xlang\compiler\dist-newstyle\build\x86_64-windows\ghc-9.4.8\compiler-0.1.0.0\opt\build

dynamic-library-dirs:
    D:\Coding\projects\Mixed\xlang\compiler\dist-newstyle\build\x86_64-windows\ghc-9.4.8\compiler-0.1.0.0\opt\build

data-dir:             D:\Coding\projects\Mixed\xlang\compiler\.
hs-libraries:         HScompiler-0.1.0.0-inplace
depends:
    aeson-2.2.3.0-09edfd31ba7327c093d123cd971e3ba787ee16f5
    aeson-pretty-0.8.10-74f8a081ddd4669a7483ec552907ddff7af0a581
    array-0.5.4.0 async-2.2.6-109dd21ffdc98605d011b242fbe3901ee392e818
    base-4.17.2.1 bytestring-0.11.5.3 containers-0.6.7
    directory-1.3.7.1 filepath-1.4.2.2
    hashable-1.4.7.0-55a0afc57081abc2b611fc3ff738d1b02781f142 mtl-2.2.2
    process-1.6.18.0
    regex-base-0.94.0.3-736beb3dada5c77e15dffbaceb7daadca1b8936c
    regex-tdfa-1.3.2.5-e75c4a9c4f162796c33e3b682aa5f53c3f1e4e48
    text-2.0.2 time-1.12.2
    unordered-con_-0.2.21-1fb444cb609ee62c2891491e46b5583b68062241

haddock-interfaces:
    D:\Coding\projects\Mixed\xlang\compiler\dist-newstyle\build\x86_64-windows\ghc-9.4.8\compiler-0.1.0.0\opt\doc\html\compiler\compiler.haddock

haddock-html:
    D:\Coding\projects\Mixed\xlang\compiler\dist-newstyle\build\x86_64-windows\ghc-9.4.8\compiler-0.1.0.0\opt\doc\html\compiler
