name:                 compiler
version:              0.1.0.0
visibility:           public
id:                   compiler-0.1.0.0-inplace
key:                  compiler-0.1.0.0-inplace
license:              MIT
maintainer:           dw725@ic.ac.uk
author:               Wang Di
abi:                  inplace
exposed:              True
exposed-modules:
    CompileJava IR.Liveness IR.Lowing IR.Optimize IR.TAC IR.TACLowing
    Lex.Token Lex.TokenPass Lex.Tokenizer Lowing.JVM Lowing.JVMJson
    Lowing.JVMLowing Parse.ParseBlock Parse.ParseExpr Parse.ParseProgm
    Parse.ParseStmt Parse.ParserBasic Parse.SyntaxTree
    Semantic.CheckProgram Semantic.ContextCheck Semantic.LibLoader
    Semantic.NameEnv Semantic.OpInfer Semantic.ReturnCheck
    Semantic.SemanticDebug Semantic.TypeCheck Semantic.TypeEnv
    Util.Basic Util.Exception Util.FileHelper Util.Type X86Lowing.ASM
    Xlang

import-dirs:
    D:\Coding\projects\Mixed\xlang\compiler\dist-newstyle\build\x86_64-windows\ghc-9.6.7\compiler-0.1.0.0\opt\build

library-dirs:
    D:\Coding\projects\Mixed\xlang\compiler\dist-newstyle\build\x86_64-windows\ghc-9.6.7\compiler-0.1.0.0\opt\build
    D:\Coding\compilers\haskell\ghcup\msys64\mingw64\lib

library-dirs-static:
    D:\Coding\projects\Mixed\xlang\compiler\dist-newstyle\build\x86_64-windows\ghc-9.6.7\compiler-0.1.0.0\opt\build
    D:\Coding\compilers\haskell\ghcup\msys64\mingw64\lib

dynamic-library-dirs:
    D:\Coding\projects\Mixed\xlang\compiler\dist-newstyle\build\x86_64-windows\ghc-9.6.7\compiler-0.1.0.0\opt\build
    D:\Coding\compilers\haskell\ghcup\msys64\mingw64\lib

data-dir:             D:\Coding\projects\Mixed\xlang\compiler\.
hs-libraries:         HScompiler-0.1.0.0-inplace
include-dirs:         D:\Coding\compilers\haskell\ghcup\msys64\mingw64\include
depends:
    aeson-2.2.3.0-1a16b58473db652d78224165acb22491141bb983
    aeson-pretty-0.8.10-63906ac1a5e392577ad9a948b857e51dd3875bf3
    array-0.5.8.0 async-2.2.6-ce9290ad24e4ee87ec8d8c8930660d5caf888fd7
    base-4.18.3.0 bytestring-0.11.5.4 containers-0.6.7
    directory-1.3.8.5 filepath-1.4.301.0
    hashable-1.5.1.0-951ef4b925faff0a29c713be474041172af33dfd mtl-2.3.1
    process-1.6.19.0
    regex-base-0.94.0.3-7a47254a787e282f5279bdcc4f93fbddd46275c7
    regex-tdfa-1.3.2.5-faac302d506846732dbb61f41b10c42b9321480e
    text-2.0.2 time-1.12.2
    unordered-con_-0.2.21-0b8ce474e75474777f6005351c94bccc16d256c8

haddock-interfaces:
    D:\Coding\projects\Mixed\xlang\compiler\dist-newstyle\build\x86_64-windows\ghc-9.6.7\compiler-0.1.0.0\opt\doc\html\compiler\compiler.haddock

haddock-html:
    D:\Coding\projects\Mixed\xlang\compiler\dist-newstyle\build\x86_64-windows\ghc-9.6.7\compiler-0.1.0.0\opt\doc\html\compiler
